# Application Configuration
replicaCount: 1

# Image Configuration
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

# Service Configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Resource Limits
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

# Ingress Configuration
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: "myapp.local"
      paths:
        - path: "/"
          pathType: "Prefix"
  tls: []

# Configuration Management
config:
  nginxConfig: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        
        location /health {
            return 200 'healthy\n';
            add_header Content-Type text/plain;
        }
        
        location / {
            try_files $uri $uri/ =404;
        }
    }

# Health Checks Configuration
probes:
  liveness:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readiness:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

# Additional Settings
labels: {}
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}