{{- if .Values.security.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-networkpolicy
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "simple-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
    {{- toYaml .Values.security.networkPolicy.ingress | nindent 4 }}
{{- end }}