{{- if and .Values.serviceAccount.create .Values.serviceAccount.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.serviceAccount.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rolebinding
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "simple-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}