apiVersion: v2
name: simple-app
description: Application simple Nginx avec ConfigMaps et Health Checks
version: 0.2.0
appVersion: "1.0.0"
type: application
keywords:
  - nginx
  - configmap
  - healthchecks
  - web
maintainers:
  - name: Kubernetes Learner
    email: learner@example.com