# Application Configuration
replicaCount: 1

# Image Configuration
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

# Service Configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Resource Limits
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

# Additional Settings
labels: {}
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

# Ingress Configuration
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: "myapp.local"
      paths:
        - path: "/"
          pathType: "Prefix"
  tls: []