# Application Configuration
replicaCount: 1

# High Availability Configuration
highAvailability:
  enabled: true   # or false if HA desactivated
  minReplicas: 3
  maxReplicas: 10
  podAntiAffinity: true
  topologyKey: "kubernetes.io/hostname"
  spreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: "ScheduleAnyway"
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: "ScheduleAnyway"
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
    # maxUnavailable: 1  # Alternative to minAvailable
  multiZone: false
  zones: []  # Example: ["us-west-2a", "us-west-2b", "us-west-2c"]

# Image Configuration
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

# Service Configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Nginx Configuration
nginxConfig:
  enabled: true
  configMapName: "nginx-config"
  # Configuration par défaut pour Nginx
  defaultConfig: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
        
        # Health check endpoint for HA
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # Redirection des erreurs vers la page d'erreur
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
        
        # Désactiver l'accès aux fichiers cachés
        location ~ /\. {
            deny all;
        }
    }
  # Configurations supplémentaires (optionnel)
  extraConfigs: {}

# Autoscaling Configuration
autoscaling:
  enabled: false
  hpaName: ""
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  # Custom metrics (example)
  # metrics:
  # - type: Pods
  #   pods:
  #     metric:
  #       name: packets-per-second
  #     target:
  #       type: AverageValue
  #       averageValue: 1k
  # Behavior configuration (optional)
  # behavior:
  #   scaleDown:
  #     stabilizationWindowSeconds: 300
  #     policies:
  #     - type: Percent
  #       value: 100
  #       periodSeconds: 15

# Resource Limits
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

# Health Checks (Enhanced for HA)
livenessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 1
  successThreshold: 1

startupProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30

# Service Account
serviceAccount:
  create: false
  name: ""

# Additional Settings
labels: {}
annotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

# Ingress Configuration
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: "myapp.local"
      paths:
        - path: "/"
          pathType: "Prefix"
  tls: []

# Monitoring and Observability
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
  prometheusRule:
    enabled: false
    rules: []